### ISSUE TITLE
can't run this

### ISSUE THREAD

**Issue by Ingo60** [Dierk/frepl-gui#2]
After having resolved all of the dependency and version number problems, it still does not run.
I guess I give up for today, I spent 4 hours to get that running, and the weekend is short.

```
ingo@obonto:~/dev/frepl-gui$ ./gradlew clean :client :run

FAILURE: Build failed with an exception.

* What went wrong:
Task 'client' not found in root project 'frepl'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace.    Run with --info or --debug option to get more log output.

BUILD FAILED
```

Why, ohh why? Before it told me the build was ok, when I just did ./gradlew?

**Comment by Ingo60** [comment]
None of the interesting tasks like run, build, installApp, etc. that are shown by ./gradlew tasks do work. I get everytime something like:

```
ingo@obonto:~/dev/frepl-gui$ ./gradlew build
:preFregeFX:compileFrege
E /home/ingo/dev/frepl-gui/preFregeFX/src/main/frege/org/frege/AllNodes.fr:15: `org.frege.FregeFX` is not a known java class
E /home/ingo/dev/frepl-gui/preFregeFX/src/main/frege/org/frege/AllNodes.fr:29: `org.frege.FregeEventHandler` is not a known java class
E /home/ingo/dev/frepl-gui/preFregeFX/src/main/frege/org/frege/AllNodes.fr:57: `org.frege.FregeChangeListener` is not a known java class
org.frege.AllNodes: build failed because of compilation errors.
Build failed.
runtime 9.192 wallclock seconds.
:preFregeFX:compileFrege FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':preFregeFX:compileFrege'.
> Process 'command '/usr/local/lib/jdk8-64/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

I guess it has something to do with build order?
Anyway, the only succesfull task I can run is 'clean'.

**Comment by Ingo60** [comment]
Indeed, it will run with the following command sequence:

```
./gradlew :prefregeFX:compileJava
./gradlew :prefregeFX:compileFrege
./gradlew run
```

However, now I have the problem of not being able to submit anything!
DIerk, are you aware that not every computer has a Cmd key?
I tried Ctrl+Enter, Alt+Enter, Shift+Enter, Alt-GR+Enter, but now I ran out of meta keys.
Nothing of the above works.

And then, when I close the app, the gradle doesn't seem to take notice? It is still in 

```
> Building 57% > :client:run
```

**Comment by Ingo60** [comment]
Final remark: I just recognized that I had to type

```
./gradlew clean :client:run
```

My error.
But still, this leads to the compilation errors from above.

**Comment by Dierk** [comment]
There should be no space inside :client:run

Dierk

sent from:mobile

**Comment by Dierk** [comment]
Yes, I kind of expected this. In Java terms it is meta key plus shortcut key - on Mac that happens to be Cmd but that changes with the platform. 
I guess I will support "any kind of extra key plus return" or so...

Dierk

sent from:mobile

**Comment by Dierk** [comment]
please pull and try again. You can now use any meta key you like plus Enter.

> > And then, when I close the app, the gradle doesn't seem to take notice? It is still in
> > 
> > > Building 57% > :client:run

This is currently due to me not shutting down the executor service and quitting the repl on
window closing.
Lots of work in that regard is still to be done.

cheers
Dierk

**Comment by Dierk** [comment]
I also added a proper window closing listener that sends :q to the console

**Comment by Ingo60** [comment]
Yes, mow I can use it.

The issue with the build order still remains to be solved.
