### ISSUE TITLE
Wish list / things to consider

### ISSUE THREAD

**Issue by Ingo60** [Dierk/frepl-gui#3]
I am aware of the fact that this is in a very early stage, nevertheless I think a can contribute something from the user perspective, so to speak:
1. I find it disturbing that the text entry is above the output. Could we switch this so that it works more like a terminal, where the input line is always at the bottom? In addtion, echoed user input could be set apart visually, so that in the output window one sees better what is the answer to what.
2. The :help window is apparently the good old Swing-Window. I am sure FX can do better and display HTML right away. (With links that don't send me to the browser ...)
3. Despite we have multi line input, the following does not work:

```
    foo a b = both even a b
       where both f a b = f a && f b
```

It appears as if spaces before the where have been removed?
Though

```
:{
foo a b = both even a b
     where both f a b = f a && f b
:}
```

still does.
1. In the long run, the :browse command should be obsoleted by an "outline view", like we have it in the eclipse plugin, only for all imported modules. So that one can navigate from module to type defined in that module to constructor/or function defined in that type.
2. I have a keyboard layout, where AltGr+Letter gives me that letter in a 𝕱𝖗𝖆𝖐𝖙𝖚𝖗 script. This does work so far in all programs, eclipse, web-browser, terminal. It doesn't in the frepl-gui, where some funny asian glyphs are substituted instead. The same happens when I copy such a letter from another window (i.e. the character map). However, when I copy the letter from the output window of the frepl (where they are occasionally correctly printed with the :t command), it suddenly accepts them!

**Comment by Dierk** [comment]
> I am aware of the fact that this is in a very early stage, nevertheless I think a can contribute something from the user perspective, so to speak:
> 
> sure. always welcome
> I find it disturbing that the text entry is above the output. Could we switch this so that it works more like a terminal, where the input line is always at the bottom?
> 
> sure. that is easy to change.

I had the same idea in the beginning. We can try various layouts.
Usually the user flow is left to right top to bottom.
it may be better to have history on the right hand side, then.

> In addtion, echoed user input could be set apart visually, so that in the output window one sees better what is the answer to what.
> 
> it is currently not echoed in the output window - only added to the history.
> I feel this needs more consideration.
> 
> The :help window is apparently the good old Swing-Window. I am sure FX can do better and display HTML right away. (With links that don't send me to the browser ...)
> 
> :help and :java are not yet touched at all.
> Despite we have multi line input, the following does not work:
> 
> ```
> foo a b = both even a b
>    where both f a b = f a && f b
> ```
> 
> It appears as if spaces before the where have been removed?
> Though
> 
> :{
> foo a b = both even a b
>      where both f a b = f a && f b
> :}
> still does.
> 
> this is an effect from your demand to run the console as a detached process :-)
> we can only send the lines of the input area one line at a time.
> if we surrounded that automatically with :{ :} then the following wouldn't work
> foo a b = 
>   a + b
> foo 1 2

What we could supply for easier editing is a shortcut that wraps a user selection in such braces.

I think we can find a solution there but it may require a change in frege-interpreter.

Thanks for your feedback (and try ctrl-L) :-)
Dierk

**Comment by Ingo60** [comment]
> I think we can find a solution there but it may require a change in frege-interpreter.

Yes. I think Marimuthu did it more complicated as it really is. Will have to look at   it and propose something.

I found myself often hitting the cursor up key, in an attempt to get the last input back. The list is nice, but cursor-up should nevertheless bring back the last command. Saves switching between mouse and keyboard.

Ctrl-L does nothing. It should bring up the file selection dialog, right?

**Comment by Dierk** [comment]
> I found myself often hitting the cursor up key, in an attempt to get the last input back. The list is nice, but cursor-up should nevertheless bring back the last command. Saves switching between mouse and keyboard.
> 
> True. Sth like Ctrl-up possibly. 
> Ctrl-L does nothing. It should bring up the file selection dialog, right?
> 
> Yep. Needs the latest commit.

**Comment by Dierk** [comment]
Moving through history is now per Ctrl-P Ctrl-N for Previous/Next just like Marimuthu did.
There also is Ctrl-B/S for Bigger/Smaller fonts (I will probably need that in a presentation tomorrow).
Ctrl-L for a file chooser dialog such that you can load a module.
Layout is changed to have the output above and the history right.
The bracing issue remains - you have to type the exact same :{ :} as in the command-line console. 
Closing of the app is now graceful.
