### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by ForNeVeR** [Dierk/frepl-gui#6]
I am getting an error while trying to build it with JDK8u31 on Windows. See the full log [on gist](https://gist.github.com/ForNeVeR/faf079ab26f100be99e7). Is it something wrong with my installation? I'm trying to invoke the following simple commands:

```
git clone git@github.com:Dierk/frepl-gui.git
cd frepl-gui
./gradlew clean :client:run
```

**Comment by Dierk** [comment]
Looks as if I didn't commit all files. Let me check. Please note that for only running the repl you can use the download. There is no need for building it yourself unless you want to tweak it.

**Comment by Dierk** [comment]
I guess you need Java 8 update 40 or higher since the compiler takes issue with the accessibility API that was introduced in u40.

**Comment by ForNeVeR** [comment]
Thank you, I've updated my JDK and the problem was fixed. You should maybe mention that requirement in Readme.

**Comment by Dierk** [comment]
True or even better put a check in the build. It checks for Java 8 but this appears to be not enough. PR welcome :-)

**Comment by ForNeVeR** [comment]
I don't think that there is an easy and conventional way to check JDK version in `build.gradle`. I think that simple requirement in the documentation would be enough.
